export { default as Contato } from './account.svg'
export { default as Email } from './email.svg'
export { default as Telefone } from './mobile.svg'
export { default as Lixeira } from './lixeira.svg'
export { default as Seta } from './arrow_back.svg'
export { default as Editar } from './edit.svg'
